//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelfirstMultitabla0820
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_DUCCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_DE_DUCCION()
        {
            this.REGISTRO_TRANSACCION_DEDUCCION = new HashSet<REGISTRO_TRANSACCION_DEDUCCION>();
        }
    
        public int D_TIPO_DEDUCCION { get; set; }
        public string NOMBRE_TIPO_DEDUCCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TRANSACCION_DEDUCCION> REGISTRO_TRANSACCION_DEDUCCION { get; set; }
    }
}
