#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDinyeccionSQLForm
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="INYECCIONSQL")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CRUDinyeccionSQLForm.Properties.Settings.Default.INYECCIONSQLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBuscarAlumnosCODIGO")]
		public ISingleResult<spBuscarAlumnosCODIGOResult> spBuscarAlumnosCODIGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO", DbType="Int")] System.Nullable<int> cODIGO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO);
			return ((ISingleResult<spBuscarAlumnosCODIGOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBuscarAlumnosDNI")]
		public ISingleResult<spBuscarAlumnosDNIResult> spBuscarAlumnosDNI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="NVarChar(9)")] string dNI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dNI);
			return ((ISingleResult<spBuscarAlumnosDNIResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarAlumnos")]
		public ISingleResult<spListarAlumnosResult> spListarAlumnos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarAlumnosResult>)(result.ReturnValue));
		}
	}
	
	public partial class spBuscarAlumnosCODIGOResult
	{
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DNI;
		
		private string _TURNO;
		
		private string _SEXO;
		
		private bool _REPETIDOR;
		
		private string _MODULO;
		
		private string _ESPECIALIDAD;
		
		public spBuscarAlumnosCODIGOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL")]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="NVarChar(10)")]
		public string TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(10)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPETIDOR", DbType="Bit NOT NULL")]
		public bool REPETIDOR
		{
			get
			{
				return this._REPETIDOR;
			}
			set
			{
				if ((this._REPETIDOR != value))
				{
					this._REPETIDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULO", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MODULO
		{
			get
			{
				return this._MODULO;
			}
			set
			{
				if ((this._MODULO != value))
				{
					this._MODULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD", DbType="NVarChar(25)")]
		public string ESPECIALIDAD
		{
			get
			{
				return this._ESPECIALIDAD;
			}
			set
			{
				if ((this._ESPECIALIDAD != value))
				{
					this._ESPECIALIDAD = value;
				}
			}
		}
	}
	
	public partial class spBuscarAlumnosDNIResult
	{
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DNI;
		
		private string _TURNO;
		
		private string _SEXO;
		
		private bool _REPETIDOR;
		
		private string _MODULO;
		
		private string _ESPECIALIDAD;
		
		public spBuscarAlumnosDNIResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL")]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="NVarChar(10)")]
		public string TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(10)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPETIDOR", DbType="Bit NOT NULL")]
		public bool REPETIDOR
		{
			get
			{
				return this._REPETIDOR;
			}
			set
			{
				if ((this._REPETIDOR != value))
				{
					this._REPETIDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULO", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MODULO
		{
			get
			{
				return this._MODULO;
			}
			set
			{
				if ((this._MODULO != value))
				{
					this._MODULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD", DbType="NVarChar(25)")]
		public string ESPECIALIDAD
		{
			get
			{
				return this._ESPECIALIDAD;
			}
			set
			{
				if ((this._ESPECIALIDAD != value))
				{
					this._ESPECIALIDAD = value;
				}
			}
		}
	}
	
	public partial class spListarAlumnosResult
	{
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DNI;
		
		private string _TURNO;
		
		private string _SEXO;
		
		private bool _REPETIDOR;
		
		private string _MODULO;
		
		private string _ESPECIALIDAD;
		
		public spListarAlumnosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL")]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="NVarChar(10)")]
		public string TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(10)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPETIDOR", DbType="Bit NOT NULL")]
		public bool REPETIDOR
		{
			get
			{
				return this._REPETIDOR;
			}
			set
			{
				if ((this._REPETIDOR != value))
				{
					this._REPETIDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULO", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MODULO
		{
			get
			{
				return this._MODULO;
			}
			set
			{
				if ((this._MODULO != value))
				{
					this._MODULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD", DbType="NVarChar(25)")]
		public string ESPECIALIDAD
		{
			get
			{
				return this._ESPECIALIDAD;
			}
			set
			{
				if ((this._ESPECIALIDAD != value))
				{
					this._ESPECIALIDAD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
