--CREAR TABLA
--alumnos
CREATE TABLE ALUMNOS (
CODIGO INT IDENTITY NOT NULL,
NOMBRE NVARCHAR(30),
DNI NVARCHAR(9) NOT NULL,
TURNO NVARCHAR(10),
SEXO NVARCHAR(10),
REPETIDOR BIT NOT NULL,
MODULO NVARCHAR(10) NOT NULL,
ESPECIALIDAD NVARCHAR(25),
CONSTRAINT PK_ALUMNOS PRIMARY KEY (CODIGO)
);