USE [master]
GO

/****** Object:  Database [REPASOLUNES]    Script Date: 22/07/2021 20:19:45 ******/
CREATE DATABASE [REPASOLUNES] ON  PRIMARY 
( NAME = N'REPASOLUNES', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSSAPH\MSSQL\DATA\REPASOLUNES.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'REPASOLUNES_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSSAPH\MSSQL\DATA\REPASOLUNES_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [REPASOLUNES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [REPASOLUNES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [REPASOLUNES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [REPASOLUNES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [REPASOLUNES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [REPASOLUNES] SET ARITHABORT OFF 
GO

ALTER DATABASE [REPASOLUNES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [REPASOLUNES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [REPASOLUNES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [REPASOLUNES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [REPASOLUNES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [REPASOLUNES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [REPASOLUNES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [REPASOLUNES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [REPASOLUNES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [REPASOLUNES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [REPASOLUNES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [REPASOLUNES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [REPASOLUNES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [REPASOLUNES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [REPASOLUNES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [REPASOLUNES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [REPASOLUNES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [REPASOLUNES] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [REPASOLUNES] SET  MULTI_USER 
GO

ALTER DATABASE [REPASOLUNES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [REPASOLUNES] SET DB_CHAINING OFF 
GO

ALTER DATABASE [REPASOLUNES] SET  READ_WRITE 
GO


