--1º)Consultar las Cuentas de los clientes cuyo Apellido empiece por A
SELECT CUENTA.IDCUENTA,CUENTA.IDCLIENTE,CLIENTE.IDCLIENTE,CLIENTE.APELLIDOS
FROM CUENTA JOIN CLIENTE
ON CUENTA.IDCLIENTE = CLIENTE.IDCLIENTE
WHERE CLIENTE.APELLIDOS LIKE 'A%';
--2º) Consulta todo los Movimientos de las Cuentas de Divisa EURO del Cliente cuyos Apellidos es PEREZ
SELECT  CLIENTE. APELLIDOS, CUENTA.IDCUENTA, MOVIMIENTO.FECHA, MOVIMIENTO.MONTO
FROM CUENTA INNER JOIN CLIENTE
ON CUENTA.IDCLIENTE = CLIENTE.IDCLIENTE
INNER JOIN MOVIMIENTO
ON CUENTA.IDCUENTA = MOVIMIENTO.IDCUENTA
WHERE CUENTA.DIVISA = 'EUROS' AND CLIENTE.APELLIDOS = 'PEREZ'
--3º) Consultar todos los movimientos de las Cuentas del Cliente PEREZ en EUROS (Aunque tenga cuentas en otras divisas) Ordenados por el número de Cuenta
SELECT CLIENTE.APELLIDOS, CUENTA.IDCUENTA, CUENTA.SALDO, CUENTA.DIVISA, MOVIMIENTO.IDMOVIMIENTO
FROM CLIENTE INNER JOIN CUENTA
ON CLIENTE.IDCLIENTE = CUENTA.IDCLIENTE
INNER JOIN MOVIMIENTO
ON CUENTA.IDCUENTA = MOVIMIENTO.IDCUENTA
WHERE CLIENTE.APELLIDOS = 'PEREZ' AND CUENTA.DIVISA = 'EUROS'
ORDER BY CUENTA.IDCUENTA
--4º) Consultar Movimientos de PEREZ y los de RODRIGUEZ
SELECT CLIENTE.APELLIDOS, CUENTA.IDCUENTA, MOVIMIENTO.IDMOVIMIENTO, MOVIMIENTO. TIPO
FROM CLIENTE INNER JOIN CUENTA
ON CLIENTE.IDCLIENTE = CUENTA.IDCLIENTE
INNER JOIN MOVIMIENTO
ON CUENTA.IDCUENTA = MOVIMIENTO.IDCUENTA
WHERE CLIENTE.APELLIDOS = 'PEREZ' OR CLIENTE.APELLIDOS = 'RODRIGUEZ'
ORDER BY CLIENTE.APELLIDOS