--5º) Crear un procedimiento almacenado para añadir clientes
CREATE PROCEDURE spAddCustomer
@IDCLIENTE VARCHAR(5),
@APELLIDOS VARCHAR(30),
@NOMBRES VARCHAR(30)
AS
INSERT INTO CLIENTE(IDCLIENTE,APELLIDOS,NOMBRES)
VALUES(@IDCLIENTE,@APELLIDOS,@NOMBRES);
--6º) Crear un procedimiento almacenado que muestre toda la informacion a partir de un IDCUENTA introducida
CREATE PROCEDURE spSearchIDCUENTA
@IDCUENTA VARCHAR(5)
AS
SELECT *
FROM CUENTA
WHERE IDCUENTA=@IDCUENTA
GROUP BY IDCUENTA;
--7º) Crear un procedimiento almacenado para eliminar un cliente
CREATE PROCEDURE spDeleteCustomer
@IDCLIENTE VARCHAR(5)
AS
DELETE FROM CLIENTE
WHERE IDCLIENTE=@IDCLIENTE;
--8º) Crear un procedimiento almacenado para modificar clientes
CREATE PROCEDURE spUpdateCustomer
@IDCLIENTE VARCHAR(5),
@APELLIDOS VARCHAR(30),
@NOMBRES VARCHAR(30)
AS
UPDATE CLIENTE
SET IDCLIENTE=@IDCLIENTE,
APELLIDOS=@APELLIDOS,
NOMBRES=@NOMBRES
WHERE IDCLIENTE=@IDCLIENTE;