--10º) Crear un procedimiento almacenado que muestre toda la informacion a partir de un campo introducido
--IDCLIENTE
CREATE PROCEDURE spSearchIDCLIENTE
@IDCLIENTE VARCHAR(5)
AS
SELECT *
FROM CLIENTE
WHERE IDCLIENTE=@IDCLIENTE
ORDER BY IDCLIENTE;


--APELLIDOS
CREATE PROCEDURE spSearchAPELLIDOS
@APELLIDOS VARCHAR(30)
AS
SELECT *
FROM CLIENTE
WHERE APELLIDOS=@APELLIDOS
ORDER BY APELLIDOS;

--NOMBRES
CREATE PROCEDURE spSearchNOMOMBRES
@NOMBRES VARCHAR(30)
AS
SELECT *
FROM CLIENTE
WHERE NOMBRES=@NOMBRES
ORDER BY NOMBRES;