--8º) Crear un procedimiento almacenado para modificar clientes
CREATE PROCEDURE spUpdateCustomer
@IDCLIENTE VARCHAR(5),
@APELLIDOS VARCHAR(30),
@NOMBRES VARCHAR(30)
AS
UPDATE CLIENTE
SET IDCLIENTE=@IDCLIENTE,
APELLIDOS=@APELLIDOS,
NOMBRES=@NOMBRES
WHERE IDCLIENTE=@IDCLIENTE;