#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsREPASOLUNES2307
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="REPASOLUNES")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::FormsREPASOLUNES2307.Properties.Settings.Default.REPASOLUNESConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddCustomer")]
		public int spAddCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, aPELLIDOS, nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteCustomer")]
		public int spDeleteCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchAPELLIDOS")]
		public ISingleResult<spSearchAPELLIDOSResult> spSearchAPELLIDOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aPELLIDOS);
			return ((ISingleResult<spSearchAPELLIDOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchIDCLIENTE")]
		public ISingleResult<spSearchIDCLIENTEResult> spSearchIDCLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<spSearchIDCLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchNOMOMBRES")]
		public ISingleResult<spSearchNOMOMBRESResult> spSearchNOMOMBRES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRES);
			return ((ISingleResult<spSearchNOMOMBRESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateCustomer")]
		public int spUpdateCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, aPELLIDOS, nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spToList")]
		public ISingleResult<spToListResult> spToList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spToListResult>)(result.ReturnValue));
		}
	}
	
	public partial class spSearchAPELLIDOSResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spSearchAPELLIDOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class spSearchIDCLIENTEResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spSearchIDCLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class spSearchNOMOMBRESResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spSearchNOMOMBRESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class spToListResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spToListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
